[tool.poetry]
name = "sp-autogen"
version = "0.1.0"
description = ""
authors = ["bwooldridge-altaml <bryan@alphalayer.ai>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
